// Generated by experiments/round6/select_zlpng.py from DEV sizes only.
#pragma once
struct ZLPNG_PolicyMember { const char* method; int codec, level, window; };
struct ZLPNG_Policy { unsigned channels, bits, count; ZLPNG_PolicyMember members[8]; };
static const char* const ZLPNG_POLICY_SHA256 = "dd51e19964584e5d78e23a1e098938080e244d975fd50d52a891723382ba44db";
static const ZLPNG_Policy ZLPNG_POLICIES[8] = {
  {1, 8, 8, {{"legacy_level1", 1, 1, 16}, {"r3_n17_t0x1x0x0x0_raw_none_interleaved_le", 1, 1, 0}, {"r3_n27_t10x0x0x4x1_left_none_interleaved_le", 1, 1, 16}, {"a_tile32_sad_full_none_planar_le", 1, 1, 16}, {"r3_n19_t8x0x0x0x0_gradient_none_interleaved_le", 1, 1, 0}, {"sample_planar", 2, 1, 0}, {"r3_n32_t256x2x0x256x1_raw_none_interleaved_le", 1, 1, 16}, {"r3_n22_t256x4x1x1x0_med_none_interleaved_le", 1, 1, 16}}},
  {1, 16, 8, {{"legacy_level1", 1, 1, 16}, {"sample_gradient_green_planar", 2, 1, 0}, {"sample_planar", 2, 1, 0}, {"r2_zigzag_t0_med_none_interleaved_split", 1, 1, 16}, {"r3_n28_t0x1x1x256x3_gradient_none_interleaved_le", 1, 1, 16}, {"r3_n16_t2x2x0x0x0_med_none_interleaved_split", 1, 1, 0}, {"r3_n24_t0x4x65535x1x1_gradient_none_interleaved_le", 1, 1, 0}, {"r3_n09_t4096x2x0x0x0_raw_none_interleaved_le", 1, 1, 0}}},
  {2, 8, 1, {{"legacy_level1", 1, 1, 16}}},
  {2, 16, 2, {{"legacy_level1", 1, 1, 16}, {"r3_n25_t6x13x0x0x0_raw_none_planar_split", 1, 1, 16}}},
  {3, 8, 8, {{"legacy_level1", 1, 1, 16}, {"r3_n24_t1x16x65535x0x1_gradient_green_interleaved_le", 1, 1, 16}, {"r3_n27_t1000x1x0x16x0_left_none_interleaved_le", 1, 1, 0}, {"r3_n21_t1x16x1x0x0_gradient_green_planar_le", 1, 1, 16}, {"r3_n24_t1x4x65535x0x1_raw_ycocg_interleaved_le", 1, 1, 0}, {"sample_med_green_planar", 2, 1, 0}, {"r3_n27_t1000x2x0x16x0_raw_none_interleaved_le", 1, 1, 16}, {"r3_n23_t0x0x1024x0x0_gradient_none_planar_le", 1, 1, 0}}},
  {3, 16, 7, {{"legacy_level1", 1, 1, 16}, {"sample_med_none", 2, 1, 0}, {"r3_n22_t256x8x1x1x0_med_none_planar_le", 1, 1, 0}, {"r3_n20_t2x1x-1x-2x0_gradient_none_planar_split", 1, 1, 0}, {"r3_n23_t0x0x1024x0x0_gradient_none_rowplanar_le", 1, 1, 0}, {"r2_zigzag_t0_med_green_planar_split", 1, 1, 16}, {"r3_n07_t64x2x1x4096x64_med_none_planar_split", 1, 1, 16}}},
  {4, 8, 8, {{"legacy_level1", 1, 1, 16}, {"r3_n24_t1x8x65535x0x1_med_none_interleaved_le", 1, 1, 0}, {"r3_n24_t1x4x255x0x1_raw_none_interleaved_le", 1, 1, 0}, {"r3_n25_t3x3x0x0x0_med_none_planar_le", 1, 1, 16}, {"r3_n24_t0x16x65535x1x1_med_none_interleaved_le", 1, 1, 0}, {"r3_n27_t2139x2x0x3x1_raw_none_interleaved_le", 1, 1, 0}, {"r3_n24_t1x16x65535x0x0_left_green_interleaved_le", 1, 1, 0}, {"r3_n17_t0x2x0x0x0_raw_none_planar_le", 1, 1, 0}}},
  {4, 16, 1, {{"legacy_level1", 1, 1, 16}}},
};
